services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mtp
    ports:
      - "5435:5432" #5432/5433/5434 are already used by native Postgres and other local projects on this machine
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
