"""add git_sub_path to build_jobs

Revision ID: 28b60868b4a0
Revises: 2010d588dd5e
Create Date: 2026-09-24 20:13:37.083199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28b60868b4a0'
down_revision: Union[str, Sequence[str], None] = '2010d588dd5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build_jobs', sa.Column('git_sub_path', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build_jobs', 'git_sub_path')
    # ### end Alembic commands ###
